### ISSUE TITLE
Initializing Prisma with Deno 

### ISSUE THREAD

**Issue by CrispenGari** [denoland/deno_std#3328]
**I'm getting an error while trying to initialize prisma using denon**

**I was following the example in the docs**
* [example](https://deno.com/manual@v1.32.3/node/how_to_with_npm/prisma)

In the example you initialize `prisma` as follows:

```shell
deno run --allow-read --allow-env --allow-write npm:prisma@^4.5 init
```
I'm initializing with the following command:

```shell
deno run --allow-read --allow-env --allow-net --allow-sys --allow-write npm:prisma@^4.5 init
```

But why am i getting the following error:

```shell
Uncaught (in promise) TypeError: context.digest is not a function
```
These are the logs:

```shell
> Downloading Prisma engines for Node-API for windows [=====               ] 24%error: Uncaught (in promise) TypeError: context.digest is not a function
    at Hash.flush [as _flush] (ext:deno_node/internal/crypto/hash.ts:47:35)
    at Hash.Ot [as _final] (ext:deno_node/_stream.mjs:11:59823)
    at Fa (ext:deno_node/_stream.mjs:11:51130)
    at Ua (ext:deno_node/_stream.mjs:11:51274)
    at mt (ext:deno_node/_stream.mjs:11:51350)
    at Hash.S.end (ext:deno_node/_stream.mjs:11:50523)
    at he.u (ext:deno_node/_stream.mjs:11:36397)
    at Object.onceWrapper (ext:deno_node/_events.mjs:502:28)
    at he.emit (ext:deno_node/_events.mjs:391:35)
    at Ea (ext:deno_node/_stream.mjs:11:43461)
```

- OS: `Window 10`
- deno version: `1.32.5`
- std version:

**Comment by iuioiua** [comment]
This issue should be in the main repo, as it's a runtime issue.

**Comment by CrispenGari** [comment]
@iuioiua So how can this issue solved?

**Comment by kt3k** [comment]
This has been fixed in https://github.com/denoland/deno/pull/18818

Please wait for the next Deno release, or downgrade Deno to 1.32.4 for the moment

**Comment by iuioiua** [comment]
@CrispenGari, are you still experiencing this issue?

**Comment by CrispenGari** [comment]
> @CrispenGari, are you still experiencing this issue? If so, opening an issue in [the main repo](https://github.com/denoland/deno) would be best.

It's now working on `deno: 1.33.1`
